"""empty message

Revision ID: 3fa7a7685193
Revises: 6388d467cd08
Create Date: 2020-01-30 18:06:38.032757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fa7a7685193'
down_revision = '6388d467cd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Run', sa.Column('predictFile', sa.PickleType(), nullable=True))
    op.drop_column('Run', 'predict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Run', sa.Column('predict', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('Run', 'predictFile')
    # ### end Alembic commands ###
