"""empty message

Revision ID: 6388d467cd08
Revises: 0d506b17353b
Create Date: 2020-01-30 18:05:27.298138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6388d467cd08'
down_revision = '0d506b17353b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Run', sa.Column('predict', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Run', 'predict')
    # ### end Alembic commands ###
