"""empty message

Revision ID: 95f0735a7c58
Revises: 9c359cfbbd60
Create Date: 2020-01-22 16:50:56.959815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f0735a7c58'
down_revision = '9c359cfbbd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Run', sa.Column('modelList', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Run', 'modelList')
    # ### end Alembic commands ###
